name: Start a new version release

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+-rc*"

env:
  CHGLOG_RELEASE: git-chglog_0.15.4_linux_amd64
  CHGLOG_PATH: https://github.com/git-chglog/git-chglog/releases/download/v0.15.4

jobs:
  initiate-version-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Register desired version
      id: release_version
      run: |
        echo "VERSION=`echo $(git describe --tags --abbrev=0|grep -Eo '[0-9]+.[0-9]+.[0-9]+')`" >> $GITHUB_OUTPUT
        echo "AUTHOR=`echo $(git log -1 --pretty=%an)`" >> $GITHUB_OUTPUT
    - name: Get git-chglog and update CHANGELOG
      run: |
        wget ${{ env.CHGLOG_PATH }}/${{ env.CHGLOG_RELEASE}}.tar.gz  # get the binary for the chglog
        tar --extract --file=${{ env.CHGLOG_RELEASE}}.tar.gz git-chglog
        ./git-chglog -o CHANGELOG.md  # update the changelog file
        rm git-chglog
    - name: Create version release Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        branch: ${{ steps.release_version.outputs.version }}
        commit-message: "automated-update of changelog"
        add-paths: |
          CHANGELOG.md
        delete-branch: false
        title: Release version ${{ steps.release_version.outputs.version }}
        body: |
          simpler
        base: main  # NOTE: this should match the branch on which the tag was made

