name: Start a new version release

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+-rc*"

jobs:
  initiate-version-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Register desired version
      id: release_version
      run: |
        echo "VERSION=`echo $(git describe --tags --abbrev=0|grep -Eo '[0-9]+.[0-9]+.[0-9]+')`" >> $GITHUB_OUTPUT
        echo "AUTHOR=`echo $(git log -1 --pretty=%an)`" >> $GITHUB_OUTPUT
    - name: Auto-update Changelog
      shell: bash
      run: |
        curl -o git-chglog -L https://github.com/git-chglog/git-chglog/releases/download/0.15.4/git-chglog_linux_amd64
        chmod u+x git-chglog
        ./git-chglog -o CHANGELOG.md
        rm git-chglog
    - name: Create version release Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        branch: ${{ steps.release_version.outputs.version }}
        commit-message: "automated-update of changelog"
        add-paths: |
          CHANGELOG.md
        delete-branch: false
        title: Release request version ${{ steps.release_version.outputs.version }}
        body: |
          This request  was triggered by **${{ steps.release_version.outputs.AUTHOR }}**
          
          The initiating tag was **${{ github.ref_name }}**

          Merging this Pull Request will create a release of the version **${{ steps.release_version.outputs.version }}**.
        labels: |
          version-release
        team-reviewers:
          admin
        base: main  # NOTE: this should match the branch on which the tag was made

