name: Prepare version release

on:
  push:
    branch:
      - "release-[0-9]+.[0-9]+.[0-9]+"

jobs:
  pre_release_checks:
    runs-on: ubuntu-latest
    steps:
      - name: smoke step
        run: |
          echo I ran
      - name: echo1
        run: |
          echo "VERSION=`echo $(${{ github.ref }}|grep -Eo '[0-9]+.[0-9]+.[0-9]+')`"
      - name: echo2
        run: |
          echo "VERSION=`echo $($github.ref|grep -Eo '[0-9]+.[0-9]+.[0-9]+')`"
      - name: echo4
        run: |
          echo $($github.ref|grep -Eo '[0-9]+.[0-9]+.[0-9]+')
      - name: echo5
        run: |
          echo "VERSION=$(echo ${{ github.ref }}|grep -Eo '[0-9]+.[0-9]+.[0-9]+')"
