name: Prepare version release

on:
  push:
    branch:
      - "release-[0-9]+.[0-9]+.[0-9]+"

jobs:
  pre_release_checks:
    if: github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: smoke step
        run: |
          echo I ran to prepare for 
          echo "VERSION=$(echo ${{ github.ref }}|grep -Eo '[0-9]+.[0-9]+.[0-9]+')"
