name: Publish a version

on:
  pull_request:
    # TODO: switch back
    # types:
    #   - closed
    branches:
      - "75-avoid-pushing-the-tag-to-main"

jobs:
  release-version:
    # if: ${{ github.event.pull_request.merged && startsWith(github.head_ref, 'release-') }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      OWNER: ${{ github.repository_owner }}
      REPO: ${{ github.event.repository.name }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Get the version to release
        id: release_version
        run: |
          git fetch --filter=tree:0 origin +refs/tags/*:refs/tags/*
          # TODO: switch back
          # echo "VERSION=$(echo ${{ github.head_ref }}|grep -Eo '[0-9]+.[0-9]+.[0-9]+')" >> $GITHUB_OUTPUT
          echo "VERSION=0.6.4" >> $GITHUB_OUTPUT
          echo "PREVIOUS_VERSION=`echo $(git tag --list | grep -E '[0-9]+.[0-9]+.[0-9]+$' | tail -n1)`" >> $GITHUB_OUTPUT
      - name: Remove previous releases of the target tag, if existing
        run: |
          if script -q -e -c "gh release view ${{ steps.release_version.outputs.version }}"; then
            # removing previous release along with associated tag
            gh release delete ${{ steps.release_version.outputs.version }} \
              --cleanup-tag -y \
              --repo ${{ env.OWNER }}/${{ env.REPO }}
          else
            # non-exist
            echo "No trace of a previous release."
          fi
          gh label create ${{ env.LABEL_CHECK }} --repo ${{ env.OWNER }}/${{ env.REPO }}
      - name: Prepare Release note
        # this gets the first the changes to the previous clean tag (including manual edits)
        run: |
          awk '/<a name="${{ steps.release_version.outputs.version }}".*/{a=1};a;/<a name="${{ steps.release_version.outputs.previous_version }}"*/{exit}' CHANGELOG.md | head -n -1 >> body.md
      - name: Create tag and release
        run: |
          gh release create ${{ steps.release_version.outputs.version }} \
            --target ${{ github.event.pull_request.head.sha }} \
            --latest \
            --title "${{ }}" \
            --notes-file body.md \
            --repo ${{ env.OWNER }}/${{ env.REPO }}
      # - name: Upload additional artifacts to the release
      #   run: |
      #     gh release upload ${{ steps.release_version.outputs.version }} \
      #       some_file.md \
      #       other_file.md \
      #       --clobber
      #       --repo ${{ env.OWNER }}/${{ env.REPO }}
